# Generated by Django 4.2.3 on 2023-07-23 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.DateField(default=1, verbose_name='Fecha Nacimiento'),
        ),
    ]
