# Generated by Django 4.2.3 on 2023-07-26 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_noticias_uptdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_noticias/'),
        ),
    ]
