# Generated by Django 4.2.3 on 2023-07-31 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='asunto',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
